### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by talumbau**

### CODE REVIEW

**Comment by talumbau** [comment]
Hmm.. looks like the Codecov is failing for me:

```
[2024-01-31T17:01:05.977Z] ['verbose'] Passed token was 0 characters long
```

is the Codecov action known to currently work?
@jdebacker

**Comment by jdebacker** [comment]
@talumbau Thanks for your work on this.  I periodically have failures to upload to Codecov, but it's intermittent and I haven't identified a cause.  I just restarted the job that failed upload and hope it will success this time.

**Comment by talumbau** [comment]
OK. Looks like CodeCov is good to go then, correct? I'll merge this if you approve.

**Comment by jdebacker** [comment]
Thanks for this TJ, just merged.

**Pull request merged**
