### PR TITLE
Fix get_tr docstring: returns transfers, not bequests

### PR DESCRIPTION
**Pull request by MaxGhenis**

### CODE REVIEW

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for fixing this typo.  It looks like a C/S tests is failing due to the version bump for Tax-Calculator, which now uses ParamTools.  Do you want to try to fix that here or shall I open another PR to fix?

**Comment by MaxGhenis** [comment]
I'm not too familiar with ParamTools so might be better to fix that in a separate PR.

**Comment by hdoupe** [comment]
Hey @MaxGhenis and @jdebacker, @Peter-Metz and have started going through the process of updating some of the cs-config code for Tax-Cruncher here: https://github.com/PSLmodels/Tax-Cruncher/pull/38.

Tax-Cruncher doesn't have the CPS/PUF distinction so it's a little more straightforward. I'm planning to do the update to account for some parameters only being compatible with one of the files tomorrow or Wednesday.

**Comment by rickecon** [comment]
Thanks for the pointer, @hdoupe.

**Comment by hdoupe** [comment]
Hi all, I've started working on converting Tax-Brain's `cs-config` package to use ParamTools: https://github.com/PSLmodels/Tax-Brain/pull/128

I moved most of the inputs processing code into the [`cs_config/inputs.py`](https://github.com/hdoupe/Tax-Brain/blob/tc30-updates/cs-config/cs_config/inputs.py) file:
- `convert_policy_defaults`: Checks the `section_1` header and data source selection to determine what defaults should be returned to C/S.
- `convert_policy_adjustment`: Converts parameters from `some_param_checkbox` to `some_param-indexed`.

**Pull request merged**
