### PR TITLE
Computing macroeconomic feedback effects on revenue

### PR DESCRIPTION
**Pull request by jdebacker**
This PR creates a function to take model output and compute the percentage change in IIT+payroll tax revenues due to macroeconomic feedback effects.  

More details of the approach are in Issue #569.

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon Here are what the percentage change decompositions are looking like for the output from `run_ogusa_example.py`:

<table border="1" class="dataframe table table-striped table-hover">  <thead>    <tr style="text-align: right;">      <th>Year</th>      <th>Variable</th>      <th>2020</th>      <th>2021</th>      <th>2022</th>      <th>2023</th>      <th>2024</th>      <th>2025</th>      <th>2026</th>      <th>2027</th>      <th>2028</th>      <th>2029</th>      <th>2020-2029</th>      <th>SS</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>Pct Change due to tax rates</td>      <td>45.91</td>      <td>44.43</td>      <td>138.60</td>      <td>284.39</td>      <td>-5,691.30</td>      <td>-251.88</td>      <td>-85.45</td>      <td>80.17</td>      <td>23.89</td>      <td>46.60</td>      <td>-536.46</td>      <td>57.23</td>    </tr>    <tr>      <th>1</th>      <td>Pct Change due to behavior</td>      <td>-8.68</td>      <td>-9.62</td>      <td>-19.62</td>      <td>-22.24</td>      <td>-33.43</td>      <td>-58.59</td>      <td>-20.75</td>      <td>-9.34</td>      <td>-8.50</td>      <td>0.34</td>      <td>-19.04</td>      <td>12.07</td>    </tr>    <tr>      <th>2</th>      <td>Pct Change due to macro</td>      <td>-2.00</td>      <td>-1.86</td>      <td>-2.33</td>      <td>-3.80</td>      <td>-2.96</td>      <td>-9.55</td>      <td>-567.60</td>      <td>53.32</td>      <td>33.10</td>      <td>18.69</td>      <td>-48.50</td>      <td>27.52</td>    </tr>  </tbody></table>

I can't quite wrap my head around why the tax rates resulting in such large percentage changes and why the macro stuff gets wild after 2026.  Need to think more about the decomposition...

**Comment by jdebacker** [comment]
Regarding the previous comment - I see the issue driving large percentage changes.  These come when there is a flip in the sign of the revenue effects (e.g., in this reform analyzed above, revenues go from positive to negative over the budget window).  Will need to think about how to deal with these.

**Comment by rickecon** [comment]
@jdebacker. We can't do percentage changes when there is a flip in sign in the baseline. We have to go with simple differences in those cases. But that is an easy check to code.

**Comment by jdebacker** [comment]
@rickecon Can you help me with the following:  I don't see how model units are helpful when we want to apply some scaling factor to static estimates from a microsimulation model.  The purpose of the proposed function is to be able to say, e.g., "when accounting for macro feedback effects, the revenue estimate goes from $1.2T to $1.0T".   For that, we need to know that macro feedback effects lower the revenue estimate by some factor, e.g., 17% (beyond changes captured by rate changes and behavior).  

How can we do this if we only have simple diffs?

**Comment by jdebacker** [comment]
Ok, as a comparison, one can consider the results above from OG-USA, simulating a repeal of the TCJA, to the dynamic analysis in JCT's [JCX-69-17 report](https://www.jct.gov/publications.html?func=startdown&id=5055).  

In doing this comparison, one finds percentage changes in revenue from the macro analysis that are similar to those outlined above - outside of the very large percentages around the time the policy moves from generating positive revenue relative to the baseline to less revenue.  

So the approach outlined seems to be consistent with the approach of JCT, with some care needed in interpreting the results when crossing a zero-threshold.

**Comment by jdebacker** [comment]
@rickecon  This PR is ready for your review.

**Pull request merged**
