### PR TITLE
Clean up equations/math within documentation

### PR DESCRIPTION
**Pull request by chusloj**
This PR addresses the equations/math/`LaTeX` issues within #643. Issues with math not rendering correctly or cleanly were addressed in the following sections:

- Stationarization
- Equilibrium
- Exogeneous parameters
- Demographics
- Lifetime earnings profiles
- Derivations

I've found a couple things for how the Jupyter Book docs process math and text in general:

- JB is very sensitive to tabs and spaces between lines, especially when it comes to inserting math.
- The [MyST guide to markdown](https://jupyterbook.org/reference/cheatsheet.html?highlight=list#lists) should be followed exactly regarding spaces and tabs for creating lists in order for JB to correctly render lists as specified.

### CODE REVIEW

**Comment by rickecon** [comment]
@chusloj Thanks for submitting this PR with these changes. I am just starting to review this. It needs a little tweaking. I will have some comments to you soon.

**Comment by chusloj** [comment]
I've also update the formatting for the `TabSSeqlbAggrVars` table in the Equilibrium section.

**Comment by chusloj** [comment]
@rickecon You mentioned today in the PSL meeting that you'd like to place a noticeable box to clearly identify the definitions for the model. In the equilibrium section, for the definitions of both steady-state and non-steady-state stationary equilibriums, I've made an attempt at that. It places the `{admonition}` box around the definitions as seen in the JB documentation [here](https://jupyterbook.org/content/content-blocks.html).

**Comment by rickecon** [comment]
@chusloj and @jdebacker. I think I prefer to have definitions be Jupyter Book `{admonitions}` that have the `note` style so they are blue. Then I think we should have propositions, proofs, lemmata, and theoremata be `{admonitions}` that have the `tip` style so they are yellow. We should save the red `warning` style for warnings, cautions, or bad things.

**Example**
Lines 186-188 of `demographics.md` could be the following:
````
```{admonition} Proposition [number]
:class: note
If the age $s=1$ immigration rate is $i_1>-(1-\rho_0)f_1$ and the other
immigration rates are strictly positive $i_s>0$ for all $s\geq 2$ such that
all elements of $\boldsymbol{\Omega}$ are nonnegative, then there exists
a unique positive real eigenvector $\boldsymbol{\bar{\omega}}$ of the
matrix $\boldsymbol{\Omega}$, and it is a stable equilibrium.
```
````

Here is what this looks like in the [Git-Tutorial](https://pslmodels.github.io/Git-Tutorial/content/background/VCgitHistory.html) Jupyter Book.

AdmonDef


I haven't figured out the right way in Jupyter Book to number definitions, theorems, etc., but there might be a way to do it in the same way that equations or figures are numbered (see Jupyter Book [referencing documentation](https://jupyterbook.org/content/citations.html#referencing-your-book-s-content)).

Jason, chime in if you agree with this approach to definitions, theorems, proofs, etc.

**Comment by jdebacker** [comment]
I'm fine with these suggested approaches to definitions, theorems, etc.

**Comment by rickecon** [comment]
@chusloj . Let us know how far you are going with this PR. I am happy to merge it when you are done. There is a lot more to do to get the Jupyter Book documentation to look like the LaTeX-produced PDF, and I am happy to take it in chunks. This is a good chunk.

cc: @jdebacker

**Comment by chusloj** [comment]
@rickecon 
> Let us know how far you are going with this PR

I am going to reformat any remaining `LaTeX`/math, figures and tables – that will finish this chunk.

**Comment by rickecon** [comment]
@chusloj. I am working on another PR to your branch for this PR. I have finished `demographics.md`, `earnings.md`, `exogenous_parameters.md`, and `tax_functions.md`. I will finish `stationarization.md` and `equilibrium.md` tomorrow. I have labeled this PR "in progress" until I submit my PR to your branch. When you merge that, it will become part of this PR and I will merge it into the main repository.

**Comment by rickecon** [comment]
@chusloj . I just submitted a PR to your `latex-update` branch. There are still changes that I want to make to `equilibrium.md`, but this current PR should be sufficient for this chunk.

**Comment by chusloj** [comment]
@rickecon Everything looks good, except there are still several bugs in `equilibrium.md` As you say, that will be addressed in another PR. Otherwise, this looks ready to merge to me.

**Comment by rickecon** [comment]
@chusloj. Yes. I gave up on fixing everything in `equilibrium.md`. We'll save that for another day. Thanks for getting this PR so far along, and for sucking me into it.

**Pull request merged**
