### PR TITLE
Add environment and instructions for running psid_download.R

### PR DESCRIPTION
**Pull request by MaxGhenis**
Been trying to run `psid_download.R` so thought I'd add some documentation and an environment file. It's not working yet, not sure why:
```
(ogusa-calibrate-dev-r) mghenis@penguin:~/PSLmodels/OG-USA-Calibration/ogusa_calibrate/data/PSID$ Rscript psid_download.R 
[1] "Directory to save files = /home/mghenis/PSLmodels/OG-USA-Calibration/ogusa_calibrate/data/PSID"
[1] "Beginning to build panel"
INFO [2021-03-01 22:50:31] Will download missing datasets now
INFO [2021-03-01 22:50:31] will download family files: 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017
INFO [2021-03-01 22:50:31] will download latest individual index: IND2017ER
This can take several hours/days to download.
 want to go ahead? give me 'yes' or 'no'.
INFO [2021-03-01 22:50:31] psidR: Loading Family data from .rda files
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: build.panel -> load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open file '/home/mghenis/PSLmodels/OG-USA-Calibration/ogusa_calibrate/data/PSID/': it is a directory
Execution halted
```
Also just a note that installing `psidR` from GitHub breaks for me too, so I'm using the CRAN `install.packages` version. Since I'm using R from `conda`, which is behind on `devtools` (v2.0.2 rather than the latest 2.3.2), the [recommended installation command](https://github.com/floswald/psidR) fails:
```
> library(devtools)
> install_github("psidR",username="floswald")
Error in parse_repo_spec(repo) : Invalid git repo specification: 'psidR'
```
When I try with the legacy syntax, I get a different error:
```
> install_github("floswald/psidR")
Downloading GitHub repo floswald/psidR@master
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error in system(cmd, intern = TRUE) : error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/Rtmp92WJD4/file13235d01547a.tar.gz' -C '/tmp/Rtmp92WJD4/remotes132371ccdeb3'’ returned error code 127
```
I haven't tried running outside of conda, as different R installations have created issues for me in the past.

@prrathi how does this compare to issues you were experiencing?

### CODE REVIEW

**Comment by jdebacker** [comment]
@MaxGhenis I believe I've only run this program successfully using a non-Conda R installation and installing `psidR` from GitHub using `devtools`.

**Comment by MaxGhenis** [comment]
I added instructions to the README with steps that I think resolved my environment issue.

However I'm hitting this issue when executing the script.
```
(base) mghenis@penguin:~/PSLmodels/OG-USA-Calibration/ogusa_calibrate/data/PSID$ Rscript psid_download.R 
/bin/bash: /home/mghenis/anaconda3/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/usr/lib/R/bin/exec/R: /home/mghenis/anaconda3/lib/libtinfo.so.6: no version information available (required by /lib/x86_64-linux-gnu/libreadline.so.7)
[1] "Directory to save files = /home/mghenis/PSLmodels/OG-USA-Calibration/ogusa_calibrate/data/PSID"
[1] "Beginning to build panel"
INFO [2021-03-02 20:37:25] Will download missing datasets now
INFO [2021-03-02 20:37:25] will download family files: 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1999, 2001, 2003, 2005, 2007, 2009, 2011, 2013, 2015, 2017
INFO [2021-03-02 20:37:25] will download latest individual index: IND2017ER
This can take several hours/days to download.
 want to go ahead? give me 'yes' or 'no'.
INFO [2021-03-02 20:37:25] psidR: Loading Family data from .rda files
Error in load(file = ind.file, envir = tmp.env) : 
  restore file may be empty -- no data loaded
Calls: build.panel -> load
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) : error reading the file
2: file ‘PSID’ has magic number ''
  Use of save versions prior to 2 is deprecated 
Execution halted
```

This seems to be from the line
```
psid_df <- build.panel(datadir=mydir, fam.vars=famvars, ind.vars=indvars, sample="SRC", design='all')
```
Others have run into this but the [suggestions](https://stackoverflow.com/questions/12463583/the-cause-of-bad-magic-number-error-when-loading-a-workspace-and-how-to-avoid) aren't super useful. This has also come up in https://github.com/floswald/psidR/issues/39, and I tried setting `data.dir=NULL` as they did, but then got this error:
```
Error in build.panel(datadir = NULL, fam.vars = famvars, ind.vars = indvars,  : 
  No .rda or .RData files found in directory
 you need to download data first.
```

**Comment by MaxGhenis** [comment]
@jdebacker would you be up to give this a shot? Or do you recall if you had some other file somewhere not in the current directory structure to make it work?

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for pinging me.  I'll take a look and see if I can provide some helpful direction.

**Comment by jdebacker** [comment]
@MaxGhenis I am able to successfully run the `psid_download.R` script in the repository.  I cannot run it from my conda R installation (which just goes on forever when I try to install `devtools`.  I need to run from RStudio ("R version 4.0.3 (2020-10-10)") and do so with the `source('psid_download.R')` in the console (otherwise I am not able to respond to the yes/no prompt to download.

**Pull request closed without merging**
