### PR TITLE
Remove small_open boolean

### PR DESCRIPTION
**Pull request by jdebacker**
This PR removes the `small_open` boolean, replacing this option with the case of `zeta_K=1` as suggested in Issue #554.

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon This PR is ready for your review when Travis CI passes.

**Comment by rickecon** [comment]
I am reviewing this right now. Will you update the `environment.yml` to include the PR #560 change of adding `ipython` as a dependency? Thx @jdebacker.

**Comment by jdebacker** [comment]
@rickecon Thanks for reviewing this.  I just updated with master to reflect newly merged PR.

FYI, test data had to change here because of bug in the case of a small open economy with a non-balanced budget and an interest rate wedge due to these lines that were in `SS.py`:
```
 if p.small_open:
        r = p.hh_r[-1]
```

**Comment by rickecon** [comment]
This PR resolves Issue #556.

**Pull request merged**
