### PR TITLE
Transition to OG-Core, Step 2: Update documentation/filenames

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds onto the work in PR #725, which modifies the code base to more to OG-Core.

In this PR, three things are accomplished:
1. Instances of "ogusa" are replaced with "ogcore" and instances of "OG-USA" are replaced with "OG-Core" (this includes directory names, virtual environment names, etc.).
2. The documentation is updated to focus on only the theoretical elements of the model that are in OG-Core (i.e., country-specific calibration documentation is moved out of this repo).
3. Files that were used by OG-USA, but will not be used by OG-Core are moved out.  These include the `regression` directory, the `cs-config` directory, files related to testing on Jenkins and documentation on readthedocs.

### CODE REVIEW

**Comment by jdebacker** [comment]
Ok - so I'm trying to run the test locally and I noticed that my find and replace `ogusa` with `ogcore` changed contents inside of pickle files that are used for tests.  This results in an error when trying to open them.  e.g.,

```
____________ ERROR collecting ogcore/tests/test_parameter_plots.py _____________
tests/test_parameter_plots.py:15: in <module>
    base_params = utils.safe_read_pickle(
utils.py:364: in safe_read_pickle
    obj = pickle.load(f, encoding='latin1')
E   _pickle.UnpicklingError: unpickling stack underflow
```

When I download the files from master, they will open, but raises an error because information in the pickled parameters object is looking for the `ogusa` package, which no longer exists:

```
____________ ERROR collecting ogcore/tests/test_parameter_plots.py _____________
ImportError while importing test module '/Users/jason.debacker/repos/dynamic/ogcore/tests/test_parameter_plots.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../anaconda3/envs/ogcore-dev/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_parameter_plots.py:15: in <module>
    base_params = utils.safe_read_pickle(
utils.py:364: in safe_read_pickle
    obj = pickle.load(f, encoding='latin1')
E   ModuleNotFoundError: No module named 'ogusa'
```

What I propose here is that I combine this PR with the solution to Issue #726.  That is, in additional to the name and documentation changes, I'll go through and update the pickle files in `test_io_data` to make sure objects that are saved are consistent with the current API.  

**I will not change any actual logic in the `.py` files**, so you can be sure that any changes in the `test_io_data` are just to streamline things and fix issues like those above.  

What do you think @rickecon?  Are you ok with this?  I wanted to do this in two separate PRs, but didn't foresee the issues with these pickle files and there are already over 200 files being changed here, so what's a few more.  

Otherwise, perhaps I can find a workaround to the above (e.g., install `ogusa` from GithHub in my `ogcore-dev` environment (alongside the `ogcore`) so I can open pickled parameters objects saved in `ogusa`.

**Comment by jdebacker** [comment]
@rickecon Let me know what you think about my question/proposal above.  Thanks!

**Comment by rickecon** [comment]
@jdebacker. Yes. Let's just do it all here. I'll review it all. Thanks for doing this trench work.

**Comment by rickecon** [comment]
@jdebacker. I've reviewed the currently 222 files that were changed. I wanted to document the 36 files that were removed to make sure they all end up in [PR #40](https://github.com/PSLmodels/OG-USA-Calibration/pull/40) of the `OG-USA-Calibration` repo or to make sure we have a reason for getting rid of them.

36 REMOVED FILES:
`.jenkins_wrapper.sh`
`.readthedocs.yml`
`.regression.txt`
`ogusa/__init__.py`
`ogusa/data/ability/FR_wage_profile_tables.xlsx`
`ogusa/data/demographic/demographic_data.csv`
`ogusa/data/demographic/mort_rates2011.csv`
`ogusa/data/demographic/mortality_rates.csv`
`ogusa/data/demographic/pop_data.csv`
`ogusa/data/labor/cps_hours_by_age_hourspct.txt`
`ogusa/data/tax_functions/TxFuncEst_baseline_CPS.pkl`
`ogusa/data/tax_functions/TxFuncEst_baseline_PUF.pkl`
`ogusa/data/wealth/scf2007to2013_wealth_age_all_percentiles.csv`
`calibration/calibrate.py`
`calibration/labor.py`
`calibration/wealth.py`
`calibration/wealthinit.py`
`cs-config/install.sh`
`cs-config/setup.py`
`cs-config/write_output.py`
`cs-config/cs_config/__init__.py`
`cs-config/cs_config/functions.py`
`cs-config/cs_config/helpers.py`
`cs-config/cs_config/tests/__init__.py`
`cs-config/cs_config/tests/test_functions.py`
`docs/book/content/calibration/UBI.md`
`docs/book/content/calibration/bequests.md`
`docs/book/content/calibration/demographics.md`
`docs/book/content/calibration/earnings.md`
`docs/book/content/calibration/exogenous_parameters.md`
`docs/book/content/calibration/macro.md`
`docs/book/content/calibration/matching_lwi.md`
`docs/book/content/calibration/tax_functions.md`
`regression/regression_results.zip`
`regression/run_reg_reforms.py`
`regression/test_regression.py`

**Comment by rickecon** [comment]
@jdebacker. You decide what logo you want for `OG-Core` from the two options in Issue #735. I'll make the `OG-Core_logo_long.png` and `OG-Core_logo_gitfig.png` versions and submit them as a PR to your branch. I am also happy to make a logo that is different. I just want something for this PR.

**Comment by jdebacker** [comment]
@rickecon Thanks for the thorough review of the changes thus far.

Here's some notes to document some of the removed files:

`ogusa/__init__.py` is not removed.  It's now at `ogcore/__init__.py`

**Need to move to OG-USA-Calibration**
* `ogusa/data/labor/cps_hours_by_age_hourspct.txt`: is used when plotting model results against the data in `output_plots.py`.  Will want to remove from this repo and place in OG-USA-Calibration, but will then need to change`output_plots.ss_profiles` to take a data argument to plot a series like this. 

**No need to replicate**:
* `.regression.txt`:Was used for testing on Jenkins, but to my knowledge, no one has used this in 5 years or so.
* `.jenkins_wrapper.sh`:Was used for testing on Jenkins, but to my knowledge, no one has used this in 5 years or so.
* `.readthedocs.yml`: API docs now created with Jupyter Book
* `ogusa/data/demographic/demographic_data.csv`: OG-USA-Calibration `demographics.py` downloads these data
* `ogusa/data/demographic/mort_rates2011.csv`: OG-USA-Calibration `demographics.py` downloads these data
* `ogusa/data/demographic/mortality_rates.csv`: OG-USA-Calibration `demographics.py` downloads these data
* `ogusa/data/demographic/pop_data.csv`: OG-USA-Calibration `demographics.py` downloads these data
* `ogusa/data/ability/FR_wage_profile_tables.xlsx`: Not used.  Regression coefficients hardcoded into `income.py`, which is already moved to OG-USA-Calibration.
* `calibration/wealth.py`: Not used.  Much of this was replicated in `ogusa/wealth.py` or other modules.
* `ogusa/data/wealth/scf2007to2013_wealth_age_all_percentiles.csv`: No longer relevant.  SCF data now read in with `ogusa/wealth.py`
* `ogusa/data/tax_functions/TxFuncEst_baseline_CPS.pkl`: No longer relevant: default tax functions parameters will be in default parameter JSON files.
* `ogusa/data/tax_functions/TxFuncEst_baseline_PUF.pkl`: No longer relevant: default tax functions parameters will be in default parameter JSON files.

**May want to move if doing regression tests**  But they will be archived in 0.6.4 for reference later if we don't want to do this now (which we might now since we almost never run these tests).
```
regression/regression_results.zip
regression/run_reg_reforms.py
regression/test_regression.py
```

**Not sure about** -- these files are old and have not been used in a while.  Some parts of them already in OG-USA-Calibrate (e.g., kernel density estimator, constructing a VCV matrix for the data moments).   They will be archived in 0.6.4 for reference later if needed as develop calibration further.
```
calibration/calibrate.py
calibration/labor.py
calibration/wealthinit.py
```

**Already moved**
```
docs/book/content/calibration/UBI.md
docs/book/content/calibration/bequests.md
docs/book/content/calibration/demographics.md
docs/book/content/calibration/earnings.md
docs/book/content/calibration/exogenous_parameters.md
docs/book/content/calibration/macro.md
docs/book/content/calibration/matching_lwi.md
docs/book/content/calibration/tax_functions.md
```

**Will want to move over to get Compute Studio set up** (though no need to do right away as OG-USA 0.6.3 already running on C/S and changes here won't affect that):
```
cs-config/install.sh
cs-config/setup.py
cs-config/write_output.py
cs-config/cs_config/__init__.py
cs-config/cs_config/functions.py
cs-config/cs_config/helpers.py
cs-config/cs_config/tests/__init__.py
cs-config/cs_config/tests/test_functions.py
```

**Comment by rickecon** [comment]
@jdebacker. This PR removes the 8 calibration chapters from the documentation. I have posted those chapters' filenames below along with their Jupyter Book reference tags in parentheses.
```
docs/book/content/calibration/UBI.md (Chap_UBI)
docs/book/content/calibration/bequests.md (Chap_Beq)
docs/book/content/calibration/demographics.md (Chap_Demog)
docs/book/content/calibration/earnings.md (Chap_LfEarn)
docs/book/content/calibration/exogenous_parameters.md (Chap_Exog)
docs/book/content/calibration/macro.md (Chap_MacroCalib)
docs/book/content/calibration/matching_lwi.md (Chap_matchingLWI)
docs/book/content/calibration/tax_functions.md (Chap_TaxCalc)
```
We need to take out from the remaining chapters any references to the reference tags to these removed chapters. In some cases, we might want to change the wording to point to the correct chapter in the country-specific documentation. I have submitted [a PR](https://github.com/jdebacker/dynamic/pull/21) to @jdebacker's source branch with my suggested changes.

**Comment by rickecon** [comment]
@jdebacker. I created a fresh conda environment `ogcore-dev` from your branch, followed by `pip install -e .` to install the `ogcore` package. I tried to run `run_examples/run_ogcore_example.py`, but it fails because of the `import taxcalc` line. We removed that dependency from `environment.yml`. And I think it is a good idea to remove that dependency from `OG-Core`. Maybe we could pip install that dependency manually in the code for `run_ogcore_example.py`. But I haven't ever done that before.

**Comment by jdebacker** [comment]
@rickecon writes:

> @jdebacker. I created a fresh conda environment ogcore-dev from your branch, followed by pip install -e . to install the ogcore package. I tried to run run_examples/run_ogcore_example.py, but it fails because of the import taxcalc line. We removed that dependency from environment.yml. And I think it is a good idea to remove that dependency from OG-Core.

Got it -- I just removed the `taxcalc` import from this script.  The PR is a WIP at the moment, though and I haven't confirms this script runs.  I want to get all tests passing first and I still have work to do there.

> Maybe we could pip install that dependency manually in the code for run_ogcore_example.py. But I haven't ever done that before.

We'll just make sure all scripts in this repo, including any example script, do not rely on `taxcalc`. The examples for country specific models will use their affiliated microsimulation model(s), such as `taxcalc`, but OG-Core won't have any of those as dependencies.

**Comment by rickecon** [comment]
@jdebacker . The changes in `text_tax.py` and `test_aggregates.py` look good to me.

**Comment by jdebacker** [comment]
@rickecon Some updates on files to move:

> Need to move to OG-USA-Calibration

> ogusa/data/labor/cps_hours_by_age_hourspct.txt: is used when plotting model results against the data in output_plots.py. Will want to remove from this repo and place in OG-USA-Calibration, but will then need to changeoutput_plots.ss_profiles to take a data argument to plot a series like this.

I changed `output_plots.ss_profiles` to it takes a data series as an argument, rather than looking for this specific file.  But I think we should not move `cps_hours_by_age_hourspct.txt` to OG-USA-Calibration.  If this file is important, OG-USA-Calibration` should include functions to create it from source data.

> Will want to move over to get Compute Studio set up (though no need to do right away as OG-USA 0.6.3 already running on C/S and changes here won't affect that):

> cs-config/install.sh
> cs-config/setup.py
> cs-config/write_output.py
> cs-config/cs_config/__init__.py
> cs-config/cs_config/functions.py
> cs-config/cs_config/helpers.py
> cs-config/cs_config/tests/__init__.py
> cs-config/cs_config/tests/test_functions.py

These are moved in [OG-USA-Calibration PR #40](https://github.com/PSLmodels/OG-USA-Calibration/pull/40)


> May want to move if doing regression tests But they will be archived in 0.6.4 for reference later if we don't want to do this now (which we might now since we almost never run these tests).
> 
> regression/regression_results.zip
> regression/run_reg_reforms.py
> regression/test_regression.py
> 

My suggestion it to not move these files.  Something like this can be created in county-specific repos if think we'll use unit testing there.

> Not sure about -- these files are old and have not been used in a while. Some parts of them already in OG-USA-Calibrate (e.g., kernel density estimator, constructing a VCV matrix for the data moments). They will be archived in 0.6.4 for reference later if needed as develop calibration further.
> 
> calibration/calibrate.py
> calibration/labor.py
> calibration/wealthinit.py

These are moved in [OG-USA-Calibration PR #40](https://github.com/PSLmodels/OG-USA-Calibration/pull/40) but will need to be cleaned up in that repo (they haven't been used in a while).

**Comment by jdebacker** [comment]
@rickecon Last two commits since your comment will be necessary for tests to pass.

I can't figure out why all the checks aren't running on this branch anymore.

**Comment by rickecon** [comment]
@jdebacker . I ran the full pytest suite and got three errors--one in `test_SS.py` and both tests in `test_execute.py`.  All three errors are `FileNotFoundError`s. It looks like it is not finding the following pickle files:
* `./ogcore/tests/test_io_data/run_SS_reform_baseline_spend_use_zeta.pkl`
* `./ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl`
* `./ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl`

```
ogcore/tests/test_SS.py .......................F.......                  [  7%]
ogcore/tests/test_TPI.py ......................                          [ 12%]
ogcore/tests/test_aggregates.py ...............................          [ 20%]
ogcore/tests/test_basic.py ....                                          [ 21%]
ogcore/tests/test_elliptical_u_est.py .......                            [ 22%]
ogcore/tests/test_execute.py FF                                          [ 23%]
ogcore/tests/test_firm.py ..........................                     [ 29%]
ogcore/tests/test_fiscal.py ...............                              [ 33%]
ogcore/tests/test_household.py ........................................  [ 42%]
ogcore/tests/test_output_plots.py .....................................  [ 51%]
ogcore/tests/test_output_tables.py .............                         [ 54%]
ogcore/tests/test_parameter_plots.py ................................... [ 63%]
                                                                         [ 63%]
ogcore/tests/test_parameter_tables.py .......                            [ 64%]
ogcore/tests/test_parameters.py .............                            [ 68%]
ogcore/tests/test_run_example.py .                                       [ 68%]
ogcore/tests/test_run_ogcore.py .                                        [ 68%]
ogcore/tests/test_tax.py ...............................                 [ 75%]
ogcore/tests/test_txfunc.py .........................                    [ 81%]
ogcore/tests/test_user_inputs.py .........                               [ 84%]
ogcore/tests/test_utils.py ............................................. [ 94%]
...................                                                      [ 99%]
ogcore/tests/test_wealth.py ..                                           [100%]
=========================== short test summary info ============================
FAILED ogcore/tests/test_SS.py::test_run_SS[Reform, baseline spending, use zeta]
FAILED ogcore/tests/test_execute.py::test_runner_baseline - FileNotFoundError...
FAILED ogcore/tests/test_execute.py::test_runner_reform - FileNotFoundError: ...
=========== 3 failed, 413 passed, 58 warnings in 19419.59s (5:23:39) ===========
```
The traceback for the `test_SS.py` failure is the following:
```
_______________ test_run_SS[Reform, baseline spending, use zeta] _______________

baseline = False, param_updates = {'baseline_spending': True, 'use_zeta': True}
filename = 'run_SS_reform_baseline_spend_use_zeta.pkl'
dask_client = <Client: 'tcp://127.0.0.1:64617' processes=7 threads=14, memory=34.36 GB>

    @pytest.mark.parametrize('baseline,param_updates,filename',
                             [
                              (True, param_updates1, filename1),
                              (False, param_updates9, filename9),
                              (True, param_updates2, filename2),
                              (False, param_updates10, filename10),
                              (True, param_updates3, filename3),
                              (True, param_updates4, filename4),
                              (False, param_updates5, filename5),
                              (False, param_updates6, filename6),
                              (False, param_updates7, filename7),
                              (False, param_updates8, filename8),
                              (False, param_updates11, filename11)
                              ],
                             ids=[
                                  'Baseline', 'Reform, baseline spending',
                                  'Baseline, use zeta',
                                  'Reform, baseline spending, use zeta',
                                  'Baseline, small open',
                                  'Baseline, small open use zeta',
                                  'Reform', 'Reform, use zeta',
                                  'Reform, small open',
                                  'Reform, small open use zeta',
                                  'Baseline, delta_tau=0'
                                  ])
    
    @pytest.mark.local
    def test_run_SS(baseline, param_updates, filename, dask_client):
        # Test SS.run_SS function.  Provide inputs to function and
        # ensure that output returned matches what it has been before.
        SS.ENFORCE_SOLUTION_CHECKS = True#False
        # if running reform, then need to solve baseline first to get values
        if baseline is False:
            p_base = Specifications(
                output_base=constants.BASELINE_DIR,
                baseline_dir=constants.BASELINE_DIR,
                baseline=True,
                num_workers=NUM_WORKERS)
            p_base.update_specifications(param_updates)
            if p_base.use_zeta:
                p_base.update_specifications({
                    'initial_guess_r_SS': 0.10, 'initial_guess_TR_SS': 0.02})
            p_base.baseline_spending = False
            base_ss_outputs = SS.run_SS(p_base, client=dask_client)
            utils.mkdirs(os.path.join(
                constants.BASELINE_DIR, "SS"))
            ss_dir = os.path.join(
                constants.BASELINE_DIR, "SS", "SS_vars.pkl")
            with open(ss_dir, "wb") as f:
                pickle.dump(base_ss_outputs, f)
        # now run specification for test
        p = Specifications(baseline=baseline, num_workers=NUM_WORKERS)
        p.update_specifications(param_updates)
        test_dict = SS.run_SS(p, client=dask_client)
>       expected_dict = utils.safe_read_pickle(
            os.path.join(CUR_PATH, 'test_io_data', filename))

ogcore/tests/test_SS.py:491: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/test_io_data/run_SS_reform_baseline_spend_use_zeta.pkl'

    def safe_read_pickle(file_path):
        '''
        This function reads a pickle from Python 2 into Python 2 or Python 3
    
        Args:
            file_path (str): path to pickle file
    
        Returns:
            obj (object): object saved in pickle file
    
        '''
>       with open(file_path, 'rb') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/test_io_data/run_SS_reform_baseline_spend_use_zeta.pkl'

ogcore/utils.py:362: FileNotFoundError
```

The traceback for the first `test_execute.py` failure is the following:
```
_____________________________ test_runner_baseline _____________________________

dask_client = <Client: 'tcp://127.0.0.1:49597' processes=7 threads=14, memory=34.36 GB>

    @pytest.mark.local
    def test_runner_baseline(dask_client):
        p = Specifications(num_workers=NUM_WORKERS)
        p.update_specifications(TEST_PARAM_DICT)
        p.baseline_dir = p.output_base = BASELINE_DIR
>       runner(p, time_path=True, client=dask_client)

ogcore/tests/test_execute.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ogcore/execute.py:45: in runner
    ss_outputs = SS.run_SS(p, client=client)
ogcore/SS.py:590: in run_SS
    ss_solutions = utils.safe_read_pickle(baseline_ss_dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl'

    def safe_read_pickle(file_path):
        '''
        This function reads a pickle from Python 2 into Python 2 or Python 3
    
        Args:
            file_path (str): path to pickle file
    
        Returns:
            obj (object): object saved in pickle file
    
        '''
>       with open(file_path, 'rb') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl'

ogcore/utils.py:362: FileNotFoundError
```

And the traceback for the second `test_execute.py` failure is the following:
```
______________________________ test_runner_reform ______________________________

dask_client = <Client: 'tcp://127.0.0.1:49597' processes=7 threads=14, memory=34.36 GB>

    @pytest.mark.local
    def test_runner_reform(dask_client):
        p = Specifications(num_workers=NUM_WORKERS)
        p.update_specifications(TEST_PARAM_DICT)
        p.baseline_dir = BASELINE_DIR
        p.output_base = REFORM_DIR
>       runner(p, time_path=False, client=dask_client)

ogcore/tests/test_execute.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ogcore/execute.py:45: in runner
    ss_outputs = SS.run_SS(p, client=client)
ogcore/SS.py:590: in run_SS
    ss_solutions = utils.safe_read_pickle(baseline_ss_dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

file_path = '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl'

    def safe_read_pickle(file_path):
        '''
        This function reads a pickle from Python 2 into Python 2 or Python 3
    
        Args:
            file_path (str): path to pickle file
    
        Returns:
            obj (object): object saved in pickle file
    
        '''
>       with open(file_path, 'rb') as f:
E       FileNotFoundError: [Errno 2] No such file or directory: '/Users/richardevans/Documents/Economics/OSE/OG-USA/ogcore/tests/OUTPUT_BASELINE/SS/SS_vars.pkl'

ogcore/utils.py:362: FileNotFoundError
```

**Comment by jdebacker** [comment]
@rickecon Thanks for running all these tests.  I think the issues were:

1. The `tests_SS.py` failure is due to me not committing a new pickle file for a new parameterization of a test we hadn't run before.
2. The failures in `test_execute.py` were because I did not include the `baseline=` argument when creating a `Specifications` class object. So when I meant for it run the baseline, it ran the reform.  Reform runs look for a pickle file from the baseline run for starting values, so this threw an error when that file wasn't found.

**Comment by rickecon** [comment]
@jdebacker . Thanks for those updates to the tests. All my processors are currently tied up with a run of the `run_ogcore_example.py` script. But everything is running well. I will rerun those three tests as soon as my example run finishes (which should be in about 1.5 hours). I expect to merge this tonight.

**Comment by rickecon** [comment]
@jdebacker . The `run_ogcore_example.py` script runs great.

**Comment by rickecon** [comment]
@jdebacker . Both tests in `test_execute.py` now pass.
```
ogcore/tests/test_execute.py ..                                               [100%]
===================== 2 passed, 8 warnings in 107.82s (0:01:47) ====================
```

**Comment by rickecon** [comment]
@jdebacker . The `test_SS.py` tests in the `test_run_SS` function all pass now. Merging.
```
ogcore/tests/test_SS.py ...........                                                     [100%]
======================== 11 passed, 13 warnings in 1084.06s (0:18:04) ========================
```

**Pull request merged**
