### PR TITLE
Remove old docs files

### PR DESCRIPTION
**Pull request by jdebacker**
This PR removes old docs files associated with the Sphinx docs and the OG-USA guide pdf file which has source file in another repo.  These have recently been replaced with the OG-USA Jupyter-Book documentation.

### CODE REVIEW

**Comment by jdebacker** [comment]
At some point, will need to take down the readthedocs page: [https://og-usa.readthedocs.io](https://og-usa.readthedocs.io) as it will no longer update after this PR.  I'm just not sure how to do that... not seeing option to delete a project from my account.

**Comment by rickecon** [comment]
@jdebacker. I would leave [OGUSAdoc.pdf](docs/OGUSAdoc.pdf) in the repository for now. There is still a lot of work to get the Jupyter Book documentation to look like the LaTeX-produced PDF. For example, I used the LaTeX-produced PDF to clean up the `demographics.md` documentation file in PR #644. There is a lot more of that still to do.

Regarding deleting the `readthedocs` site, I found this [StackOverflow link](https://stackoverflow.com/questions/48062993/is-there-a-way-to-delete-a-project-on-readthedocs-org) that seems like it is the answer.

**Comment by jdebacker** [comment]
Ok - I thought things would be in good enough shape after PR #644.  

We can let this sit until we're ready to remove the PDF.

I'll take down the readthedocs when this PR is merged.  Thanks for the link.

**Comment by rickecon** [comment]
@jdebacker. I think we should move ahead with this PR and remove the `readthedocs` files and site. I just think we should keep the `OGUSAdoc.pdf` in place until the Jupyter Book documentation is closer. Of particular value are tables, figures, equations, and definition-type items. Let me know when you think this is ready.

**Comment by jdebacker** [comment]
@rickecon Latest commit adds back the `OGUSAdoc.pdf`.

**Pull request merged**
