### PR TITLE
Jupyter-Book fixes

### PR DESCRIPTION
**Pull request by jdebacker**
This PR fixes the issues in the Jupyter Book documentation pointed out in Issue #613

### CODE REVIEW

**Comment by prrathi** [comment]
I was going to go through some of the formatting issues in Issue #613 and correct those, which ones were corrected with these fixes?

**Comment by jdebacker** [comment]
@prrathi the one commit in this PR thus far just fixes the issues with footnotes.

When you begin please open a PR immediately on a new branch or work off this one. That way I can see what you do and avoid overlap.

**Comment by jdebacker** [comment]
@prrathi I've just merged this branch to master.  I will check off the items I addressed in Issue #613 and then stop working on these issues.  I look forward to your contributions here!

**Comment by prrathi** [comment]
Got it

**Pull request merged**
