### PR TITLE
Add inequality tables

### PR DESCRIPTION
**Pull request by jdebacker**
This PR will add a couple tables showing steady-state inequality to the `output_tables.py` module.  These tables are noted in Issue #92

### CODE REVIEW

**Comment by jdebacker** [comment]
Overall inequality table:

```
import ogusa.output_tables as ot
import pickle
base_ss = pickle.load(open('./run_examples/CBO/OUTPUT_BASELINE/partial/SS/SS_vars.pkl', 'rb'))
base_params = pickle.load(open('./run_examples/CBO/OUTPUT_BASELINE/partial/model_params.pkl', 'rb'))
reform_ss = pickle.load(open('./run_examples/CBO/OUTPUT_REFORM_EXPECTED/partial/SS/SS_vars.pkl', 'rb'))
reform_params = pickle.load(open('./run_examples/CBO/OUTPUT_REFORM_EXPECTED/partial/model_params.pkl', 'rb'))
ot.ineq_table(base_ss, base_params, reform_ss, reform_params, var_list=['cssmat', 'bssmat_splus1', 'yss_before_tax_mat'],
             table_format='html')
```

'<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Steady-State Variable</th>      <th>Inequality Measure</th>      <th>Baseline</th>      <th>Reform</th>      <th>% Change</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>Consumption ($\\bar{c}_{j,s}$)</td>      <td>Gini Coefficient</td>      <td>0.258</td>      <td>0.258</td>      <td>0.137</td>    </tr>    <tr>      <th>1</th>      <td></td>      <td>Var of Logs</td>      <td>0.189</td>      <td>0.189</td>      <td>0.012</td>    </tr>    <tr>      <th>2</th>      <td></td>      <td>90/10 Ratio</td>      <td>2.817</td>      <td>2.821</td>      <td>0.155</td>    </tr>    <tr>      <th>3</th>      <td></td>      <td>Top 10% Share</td>      <td>0.222</td>      <td>0.224</td>      <td>0.943</td>    </tr>    <tr>      <th>4</th>      <td></td>      <td>Top 1% Share</td>      <td>0.043</td>      <td>0.043</td>      <td>1.344</td>    </tr>    <tr>      <th>5</th>      <td>Savings ($\\bar{b}_{j,s+1}$)</td>      <td>Gini Coefficient</td>      <td>0.546</td>      <td>0.541</td>      <td>-0.997</td>    </tr>    <tr>      <th>6</th>      <td></td>      <td>Var of Logs</td>      <td>1.396</td>      <td>1.386</td>      <td>-0.703</td>    </tr>    <tr>      <th>7</th>      <td></td>      <td>90/10 Ratio</td>      <td>21.975</td>      <td>21.572</td>      <td>-1.835</td>    </tr>    <tr>      <th>8</th>      <td></td>      <td>Top 10% Share</td>      <td>0.371</td>      <td>0.363</td>      <td>-2.263</td>    </tr>    <tr>      <th>9</th>      <td></td>      <td>Top 1% Share</td>      <td>0.064</td>      <td>0.065</td>      <td>0.238</td>    </tr>    <tr>      <th>10</th>      <td>Before-tax Income</td>      <td>Gini Coefficient</td>      <td>0.367</td>      <td>0.368</td>      <td>0.265</td>    </tr>    <tr>      <th>11</th>      <td></td>      <td>Var of Logs</td>      <td>0.408</td>      <td>0.411</td>      <td>0.865</td>    </tr>    <tr>      <th>12</th>      <td></td>      <td>90/10 Ratio</td>      <td>5.391</td>      <td>5.417</td>      <td>0.490</td>    </tr>    <tr>      <th>13</th>      <td></td>      <td>Top 10% Share</td>      <td>0.277</td>      <td>0.279</td>      <td>0.837</td>    </tr>    <tr>      <th>14</th>      <td></td>      <td>Top 1% Share</td>      <td>0.059</td>      <td>0.054</td>      <td>-8.471</td>    </tr>  </tbody></table>'

**Comment by jdebacker** [comment]
@rickecon This PR is ready for your review

**Comment by rickecon** [comment]
@jdebacker . This is really nice. I especially like the `Inequality()` class in the `ogusa/utils.py()` function with the `type={'overall', 'age', 'ability'}` option. And I love the `wealth.py` module. In `wealth.py`, lines 21 and 22, am I correct that this requires the `CUR_PATH/Data/Survey_of_Consumer_Finances/` directory and data to be present? All I can see there right now is `ogusa/Data/wealth/scf2007to2013_wealth_age_all_percentiles.csv`. Are we missing a directory and a data file?

**Comment by jdebacker** [comment]
@rickecon Yes - the `wealth` module does require the `OG-USA/Data/Survey_of_Consumer_Finances/` directory.  I would rather not put those SCF files on GitHub.  There are 3 years worth, ranging from 35.1 to 46.2MB.  I'd rather we just have anyone interested in using these to get them from us and put them in that path.  **Note that that only part of OG-USA that uses those files is in creating the table of data vs model moments from the wealth distribution.**

We've talked about this before, but my ideal scenario is that we move all raw data and calibration files into a separate repository (or repositories).  Therefore I'm not inclined to add these files and bloat the repo and OG-USA package further when they'll only be there for a limited amount of time and are unlikely to be used by most users.  Something we should think about when doing that: what is the ideal solution for a place to put all the data files (including those over the GitHub size limit) into an easily accessible place in the cloud?

**Pull request merged**
