### PR TITLE
Load 2017_law.json from the installed taxcalc version in run_ogusa_example.py

### LINKED ISSUE #607: run_ogusa_example.py reads the latest 2017_law.json, which causes an error with parameter_indexing_CPI_offset
When running `run_ogusa_example.py` (and following other instructions with the conda environment and on the latest version), I get 

```
2017 parameter_indexing_CPI_offset is an unknown parameter name
```

in a couple places.

Here's the full error log: https://gist.github.com/MaxGhenis/21eef37a722773d0ced4900f276a5c54

I think this is because it reads https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/2017_law.json#L29 from master, but the `ogusa-dev` conda environment installs the `taxcalc 2.9.0`, which hasn't reflected the change from `CPI_offset` to `parameter_indexing_CPI_offset` (@Peter-Metz made this change in https://github.com/PSLmodels/Tax-Calculator/commit/8ad6a2e3353331b533664c78936120d19783d28a).

It [might be possible](https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo) to get the version of `2017_law.json` from a URL corresponding to the latest release, but the ideal solution IMO would be `taxcalc` exposing the reform `json` files through the package to avoid having to read them from the web. I'll file an issue there now for this.

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #607 

I'm currently running `run_examples.py` to test it out.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
I think this worked, as it got well past where it previously failed dealing with the reform file, but I hit a different error at the end:
```
Time path iteration complete.
It took 23807.388461351395 seconds to get that part done.
run time =  23807.39177799225
Traceback (most recent call last):
  File "run_ogusa_example.py", line 126, in <module>
    main()
  File "run_ogusa_example.py", line 111, in main
    num_years=10, start_year=og_spec['start_year'])
  File "/home/mghenis/PSLmodels/OG-USA/ogusa/output_tables.py", line 51, in macro_table
    assert (base_params.start_year == reform_params.start_year)
AssertionError
```

**Comment by MaxGhenis** [comment]
I think my latest commit will fix the `start_year` error. It takes about 6 hours on my computer so I'll run it overnight tonight to check.

**Comment by rickecon** [comment]
@MaxGhenis. I just ran `run_ogusa_example.py` on my machine in just over 3 hours. Works great. I have not run all the `pytest` non-CI tests yet. @jdebacker.

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for this PR!  Merging.

**Pull request merged**
