### PR TITLE
Clean txfunc py

### PR DESCRIPTION
**Pull request by duncanhobbs**
This pull request addresses some of the issues raised in issue \#468.

1. Replaces `beg_yr `with `start_year` for consistency.

2. Replaces `BW` with `tpers` for consistency.

3. In the function `tax_func_loop`

4. Edits `plot_txfunc_v_data()` to only use `plot_full` boolean.

### CODE REVIEW

**Comment by jdebacker** [comment]
@duncanhobbs Thank you for opening this PR!  Things look good here on Travis CI, but there's at least one test in `test_txfunc.py` that is too long to run on Travis CI.  Can you run the `test_txfunc.py` tests on this branch and confirm they all pass?  With that, I'll go ahead and merge this PR.  Thanks!

**Comment by duncanhobbs** [comment]
When I run the test on my Windows 7 machine I get an error in [line 127](https://github.com/PSLmodels/OG-USA/blob/4e2adf0b10605e725e3cf6a0278f7c8b7cd76997/ogusa/tests/test_txfunc.py#L127) of `test_txfunc.py` with the `safe_read_pickle` function. 

The problem arises in [line 352](https://github.com/PSLmodels/OG-USA/blob/4e2adf0b10605e725e3cf6a0278f7c8b7cd76997/ogusa/utils.py#L352) of `utils.py`

The error in the safe_read_pickle function is: "No module named 'copy reg\r"

Is this because the Python3 module name is `copyreg` and not `copy_reg`?

Or is it something to do with the different way Windows and Unix systems treat newline characters?

I am using the ogusa-dev environment and Python 3.7.

I will try to run the test on my personal Mac and see if it works.

**Comment by jdebacker** [comment]
@duncanhobbs Thanks for running those tests.  I have never seen the error you found.  I'm confused though, since I don't see `copyreg` or `copy_reg` imported or references anywhere.   It's also not a package that is present in my environment when I run OG-USA on my Mac.

Let me know what you find on your Mac and I'll do some more research about what this might be related to also.

**Comment by jdebacker** [comment]
@duncanhobbs On your Windows machine, you might replace the code `safe_pickle_load()` with:
```
with open(file_path, 'rb') as f:
      try:
          obj = pickle.load(f, encoding='latin1')
      except TypeError:
          obj = pickle.load(f)
      except ImportError:
          a = f.readlines() #read pickle file line by line
          obj = map(lambda x:x.replace("\r\n","\n"),a)  # replace \r\n with \n
  return obj
```

I saw this in the SO thread [here](https://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle?rq=1).

Let me know if that works.

**Comment by duncanhobbs** [comment]
@jdebacker 

When I ran the test with the new code in Windows I got an error: `too many values to unpack expected 6 got 0.`

I also downloaded the OG-USA master branch to my Mac, activated the development environment, installed ogusa, and ran the tests just to see if they worked before I modified anything. I got an error from the assert allclose(expected_tuple, test_tuple) line in [`test_txfunc.py`](https://github.com/PSLmodels/OG-USA/blob/4e2adf0b10605e725e3cf6a0278f7c8b7cd76997/ogusa/tests/test_txfunc.py#L139)

test tuple:

```
(array([ 6.37000261e-22,  2.73413298e-03,  1.49073835e-08,  1.39727771e-02,\n        
2.32796890e-01, -3.69059719e-02,  1.00000000e-04, -1.01967001e-01,\n        
3.96030005e-02,  1.02987671e-01, -1.30433574e-01,  1.00000000e+00])
```

expected tuple:

```
array([ 6.37000261e-22,  2.73404765e-03,  1.62463424e-08,  1.48147213e-02,\n        
2.32797191e-01, -3.69059719e-02,  1.00000000e-04, -1.01967001e-01,\n        
3.96030035e-02,  1.02987671e-01, -1.30433574e-01,  1.00000000e+00]))
```

Some of the numbers don't match. This is probably because of the scipy error you mention in the code.

All of the other tests pass.

I also tested the development branch I have been working on on my Mac.

All of the tests pass except the assert `np.allclose` test mentioned above.

```
(ogusa-dev) Duncans-MacBook-Air:OG-USA duncanhobbs$ git checkout -b clean-txfunc-py origin/clean-txfunc-py
M       ogusa/tests/test_txfunc.py
Branch 'clean-txfunc-py' set up to track remote branch 'clean-txfunc-py' from 'origin'.
Switched to a new branch 'clean-txfunc-py'
(ogusa-dev) Duncans-MacBook-Air:OG-USA duncanhobbs$ cd ogusa/tests
(ogusa-dev) Duncans-MacBook-Air:tests duncanhobbs$ pytest test_txfunc.py
/Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
=================================================== test session starts ====================================================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA, inifile: setup.cfg
plugins: xdist-1.28.0, forked-1.0.2, pep8-1.0.6
collected 12 items                                                                                                         

test_txfunc.py .....F......                                                                                          [100%]

========================================================= FAILURES =========================================================
_____________________________________________________ test_txfunc_est ______________________________________________________

    @pytest.mark.full_run  # only marking as full run because platform
    # affects results from scipy.opt that is called in this test - so it'll
    # pass if run on Mac with MKL, but not necessarily on other platforms
    def test_txfunc_est():
        # Test txfunc.txfunc_est() function.  The test is that given
        # inputs from previous run, the outputs are unchanged.
        input_tuple = utils.safe_read_pickle(
            os.path.join(CUR_PATH, 'test_io_data/txfunc_est_inputs.pkl'))
        (df, s, t, rate_type, output_dir, graph) = input_tuple
        tax_func_type = 'DEP'
        numparams = 12
        test_tuple = txfunc.txfunc_est(df, s, t, rate_type, tax_func_type,
                                       numparams, output_dir, graph)
        expected_tuple = (np.array([
            6.37000261e-22, 2.73404765e-03, 1.62463424e-08, 1.48147213e-02,
            2.32797191e-01, -3.69059719e-02, 1.00000000e-04, -1.01967001e-01,
            3.96030035e-02, 1.02987671e-01, -1.30433574e-01,
            1.00000000e+00]), 19527.162030047846, 3798)
        for i, v in enumerate(expected_tuple):
>           assert(np.allclose(test_tuple[i], v))
E           assert False
E            +  where False = <function allclose at 0x104b53a60>(array([ 6.37000261e-22,  2.73413298e-03,  1.49073835e-08,  1.39727771e-02,\n        2.32796890e-01, -3.69059719e-02,  1.00000000e-04, -1.01967001e-01,\n        3.96030005e-02,  1.02987671e-01, -1.30433574e-01,  1.00000000e+00]), array([ 6.37000261e-22,  2.73404765e-03,  1.62463424e-08,  1.48147213e-02,\n        2.32797191e-01, -3.69059719e-02,  1.00000000e-04, -1.01967001e-01,\n        3.96030035e-02,  1.02987671e-01, -1.30433574e-01,  1.00000000e+00]))
E            +    where <function allclose at 0x104b53a60> = np.allclose

test_txfunc.py:140: AssertionError
===================================================== warnings summary =====================================================
/Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:431
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:431: DeprecationWarning: invalid escape sequence \h
    '''

/Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:780
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:780: DeprecationWarning: invalid escape sequence \h
    '''

/Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/heapdict.py:11
  /Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/heapdict.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class heapdict(collections.MutableMapping):

/Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/jinja2/runtime.py:318
  /Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/jinja2/runtime.py:318: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Mapping

/Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/_pytest/mark/structures.py:332
  /Users/duncanhobbs/anaconda/envs/ogusa-dev/lib/python3.7/site-packages/_pytest/mark/structures.py:332: PytestUnknownMarkWarning: Unknown pytest.mark.full_run - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

ogusa/tests/test_txfunc.py::test_find_outliers[2]
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:512: RuntimeWarning: invalid value encountered in greater
    thresh2 = (sse_mat_new[sse_mat_new > 0].mean() + se_mult *

ogusa/tests/test_txfunc.py::test_find_outliers[2]
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:513: RuntimeWarning: invalid value encountered in greater
    sse_mat_new[sse_mat_new > 0].std())

ogusa/tests/test_txfunc.py::test_find_outliers[2]
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:514: RuntimeWarning: invalid value encountered in greater
    sse_big_mat += sse_mat_new > thresh2

ogusa/tests/test_txfunc.py::test_find_outliers[2]
  /Users/duncanhobbs/Documents/GitHub/PSL/OG-USA/ogusa/txfunc.py:555: RuntimeWarning: invalid value encountered in greater
    if (sse_mat_new > thresh2).sum() > 0:

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===================================== 1 failed, 11 passed, 9 warnings in 11.24 seconds =====================================
```


Let me know if there is anything else you want me to do.

**Comment by jdebacker** [comment]
@duncanhobbs Ok - this sounds good.  Thank you for running the tests on two different platforms locally.  I feel comfortable with the results and will merge this PR.

**Pull request merged**
