### PR TITLE
Add a macro parameters calibration chapter to JB

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds a skeleton chapter to the Jupyter Book doc that begins to outline the calibration of parameters using macroeconomic data.

### CODE REVIEW

**Comment by jdebacker** [comment]
[PR #3](https://github.com/jdebacker/OG-USA-Calibration/pull/3) to the OG-USA-Calibration repo adds a script to compute several of these macro parameters in a way that is easy to update as new data are released. 

Values computed there for 2019Q1:
```
{'initial_debt_ratio': 0.7683454217979951, 'alpha_T': 0.060612831508488306, 'alpha_G': 0.08604288007341025, 'gamma': 0.38009209667935095, 'g_y': 0.018851029009258016, 'r_gov_shift': 1.0742267011470061, 'r_gov_scale': -2.87229576278685}
```

**Comment by MaxGhenis** [comment]
Another potential layout for this file could be the way taxcalc shows its policy parameters, where each parameter name is a heading (https://pslmodels.github.io/Tax-Calculator/guide/policy_params.html). This would be more API-focused, at the cost of consistency with the rest of the calibration section which is more of a textbook. If the parameter name and the default value could be in a consistent place in the section somewhere though, that could ease discovery for API users.

**Comment by jdebacker** [comment]
@MaxGhenis I like that TC approach and would like to have it *in addition to* how we've been outlining the calibration.  What I'd like to do is figure out a way to create a file similar to [`policy_params.md`](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/guide/policy_params.md), but where that file is auto filled from the `default_parameters.json` file, so that it is easy to retain consistency between the two.  Any suggestions on that?

**Comment by MaxGhenis** [comment]
`policy_params.md` is automatically generated from [`policy_current_law.json`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json) using [`make_uguide.py`](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/guide/make/make_uguide.py) and [`make_params.py`](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/guide/make/make_params.py).

**Comment by rickecon** [comment]
@jdebacker @MaxGhenis . This looks great to me. Is it ready to be merged?

**Comment by jdebacker** [comment]
@rickecon Hold off a day -- I'll try to create the additional page modeled of the Tax-Calc presentation of parameters tonight.

**Comment by rickecon** [comment]
OK @jdebacker. Let me know when that is ready for review.

**Comment by jdebacker** [comment]
@rickecon I review the scripts @MaxGhenis created in the Tax-Calc repo and that's going to be a little too involved for me to bring them over to OG-USA right now.  Therefore, this PR is ready for your review.  Thanks!

**Comment by rickecon** [comment]
@jdebacker . Are we sure that we want `parameters_metadata.json` gone. I don't remember what that file's purpose was beyond what is in `default_parameters.json`. Are we just bailing on the `"irs_ref"` and `"col_label"` fields?
```json
{
    "g_y_annual":{
        "long_name": "Growth rate of technology",
	    "description": "This parameter gives the underlying growth rate for labor augmenting technological change.  The growth rate determines long-run economic growth in OG-USA.",
        "irs_ref": "",
        "notes": "",
        "col_label": ["Growth rate of technology"]
    },
    "frisch":{
        "long_name": "Frisch elastictiy of labor supply used to fit elliptical utility",
	    "description": "The Frisch elasticity gives the elasticity of labor supply to changes in the net of tax wage rate, holding wealth constant.   This means that the Frisch elasticity captures the substitution effects, but not the income effects, of a change in the net of tax wage rate.  A Frisch elasticity of 0.4 would indicate that if the net of tax wage rate increases by 10% then hours worked would increase by 4%, if wealth were held constant.  Note that OG-USA uses an elliptical utility function for labor supply.  We parameterize this function to fit a constant Frisch elasticity function with a Frisch elasticity as input here.",
        "irs_ref": "",
        "notes": "",
        "col_label": ["Frisch elasticity"],
        "validations": {"min": 0.1, "max": 0.8 }
      },
      "world_int_rate":{
        "long_name": "World interest rate",
        "description": "World interest rate",
        "irs_ref": "",
        "notes": "",
        "col_label": ["World interest rate"],
        "validations": {"min": -0.8, "max": 0.8 }
    }
}
```

**Comment by jdebacker** [comment]
@rickecon Yes, I think we can remove this.  The file was only references in `setup.py` and all that information is now in `default_parameters.json`.  I believe `parameters_metadata.py` was left over from when we had an OG-USA app on the OSPC site.

`irs_ref` was never used here  - it was from the template used by the old Tax-Brain from the OSPC site. `col_label` labeled the parameter input on the old OSPC app, I believe.

**Pull request merged**
