### PR TITLE
OG-USA handling of UBI

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates OG-USA to properly handle the UBI estimates from Tax-Calculator.  Background discussion for this PR can be found in Issue #572.

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker and @MaxGhenis. The correct way to incorporate UBI from [Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator) into OG-USA is through the effective tax rate function and not through the marginal tax rate functions. The household budget constraint is the following:
HHBC
UBI will enter the OG-USA model exclusively through the tax liability term T_{s,t}, which is the last term in the budget constraint. The net tax liability is defined as an effective tax rate because it is easier to estimate an effective tax rate function `tau` than it is to estimate a net tax liability function `T`. Let `T_0` be the net tax liability without UBI. Then `T_0` is defined as the following,
ETR0
where `tau_0` is the effective tax rate without UBI, `x` is total labor income, `y` is total capital income, and `x + y` is total income. The difficulty is that `x + y` does not include other types of income like UBI. So we need a new effective tax rate function `tau_1` that incorporates UBI so that the net tax liability `T_1`.

The simplest conceptual specification is to have the new net tax liability with UBI `T_1` equal the original tax liability minus the UBI payment.
T1_simple
But it is difficult to get the units right of UBI dollars from the data to model units. Note that the first term on the right-hand-side of the equivalence is just `T_0` the net tax liability without UBI. So what we want to do is specify a new effective tax rate `tau_1` such that multiplying it by model income `x + y` without UBI income gives the same net tax liability `T_1` with UBI specified above.
T1_new
The effective tax rate is defined in line 188 of [`get_micro_data.py`](https://github.com/PSLmodels/OG-USA/blob/master/ogusa/get_micro_data.py#L188) as the following:
```python
'etr': calc1.array('combined') / calc1.array('expanded_income')
```
The only change that needs to be made is to subtract UBI from the numerator, and not the denominator.
```python
'etr': (calc1.array('combined') - UBI) / calc1.array('expanded_income')
```

**Comment by jdebacker** [comment]
I agree with most of what @rickecon  said, however, I do think `expanded_income` needs to be modified in the definition of the ETR to correctly map to the income definitions in OG-USA.

In particular `expanded_income != x+y`, but rather `expanded_income = x+y+UBI+consumption value of other benefits in TC`.

Therefore, for the ETR to correctly reflect the `tau_1` above, we need to defined it as:
```
'etr': (calc1.array('combined') - UBI) / (calc1.array('expanded_income')  - UBI - other benefits from TC)
```

**Comment by rickecon** [comment]
@jdebacker . I think you're right. The denominator in the ETR calculation in `get_micro_data.py` needs to be as similar as possible to our denominator in the OG-USA model, which is only labor income and capital income.

**Comment by jdebacker** [comment]
@rickecon This PR is now ready for review.

**Pull request merged**
