### PR TITLE
Describe additional tax functions

### PR DESCRIPTION
**Pull request by jdebacker**
This PR addresses Issue #616 by describing the three alternative tax functions users can select:

1. `DEP_totalinc`
2. Gouveia and Strauss (1994) functional form.
3. Linear tax functions

In addition, the `age_specific` and `analytical_mtr` options are noted.

### CODE REVIEW

**Comment by jdebacker** [comment]
I am having some trouble with enumerated lists that have items inserted between the enumerated points:

Screen Shot 2020-11-18 at 8 46 58 PM

Suggestions to fix this behavior?

**Comment by jdebacker** [comment]
Fixed list issue:
Screen Shot 2020-11-19 at 8 45 09 PM

**Comment by rickecon** [comment]
@jdebacker Was the solution to the math equation in the middle of the numbered list simply just indentation?

Let me know when you've added everything you want to add to this documentation PR.

**Comment by jdebacker** [comment]
> Was the solution to the math equation in the middle of the numbered list simply just indentation?

Yes.  Jupyter Book seems to be really finicky in this way!

This is ready for your review and merging when you deem ready @rickecon.  Thanks!

**Comment by rickecon** [comment]
@jdebacker . It looks like something in `test_utils.py`'s `test_fetch_files_from_web()` test is failing.
Fail
I restarted the tests and am looking into the failure.

**Comment by rickecon** [comment]
@jdebacker. It failed in the same place upon rerunning the `Build and test` CI tests.

**Comment by rickecon** [comment]
@jdebacker. I am merging this now, as it has passed all its tests. I ran the "Build and Test" CI twice and it failed both times. Any idea how it passed this time?

Merging.

**Comment by MaxGhenis** [comment]
From today's chat, below are the [specs on GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources); I couldn't find them for Travis.
>Each virtual machine has the same hardware resources available.
>* 2-core CPU
>* 7 GB of RAM memory
>* 14 GB of SSD disk space

**Pull request merged**
