### PR TITLE
Update documentation to remove OG-USA-Calibration references

### PR DESCRIPTION
**Pull request by rickecon**
This PR makes documentation updates and edits, mostly motivated by the need to remove `OG-USA-Calibration` references from the documentation.

* Adds core maintainers to `README.md`
* Adds middle initial to "Richard W. Evans" in `PSL_catalog.json`
* Updated reference and citation location and organization in documentation
* Removed references to `OG-USA-Calibration` from documentation

@jdebacker

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon Thanks for these updates.  Let me know when you are ready for this PR to be reviewed and merged.

**Comment by rickecon** [comment]
@jdebacker. I think this PR is ready for your review.

**Comment by jdebacker** [comment]
@rickecon Everything looks good here.  Thanks for figuring out the issue with the JB docs API section headings.

I have a PR open to your `docs` branch to make some more minor changes to avoid warnings when building the book.  Some remain, but I am unsure how to fix and they don't seem to impact the final book (e.g., warnings about docstring of  `demographics.get_pop_objs` but the API docs still build in a way you can read the return arguments - though it's not perfect).

**Comment by jdebacker** [comment]
Thanks @rickecon!  Merging.

**Pull request merged**
