### PR TITLE
Add business tax and additional breakouts to revenue decomposition

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds business tax revenue changes and additional breakouts when decomposing the overall revenue effects measured in OG-USA in the `output_tables.dynamic_revenue_decomposition()` function.

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon This PR is ready for review.

**Comment by rickecon** [comment]
@jdebacker. I can't figure out why the codecov/project is failing. In the details, it says that code coverage in `TPI.py` went down to 75% because of this PR. That doesn't make any sense to me.

**Comment by rickecon** [comment]
@jdebacker . Do you care about updating the docstring in this branch's `output_tables.py` lines 445 to 461? This PR introduces an extra business tax line to the decomposition.

**Comment by rickecon** [comment]
@jdebacker. This looks different than I thought we discussed on the phone today. I thought we were going to do the following:
* Series A: total tax revenue, baseline variables = [IIT, CIT, behavior, macro], reform variables = []
* Series B: total tax revenue, baseline variables = [CIT, behavior, macro], reform variables = [IIT]
* Series C: total tax revenue, baseline variables = [behavior, macro], reform variables = [IIT, CIT]
* Series D: total tax revenue, baseline variables = [macro], reform variables = [IIT, CIT, behavior]
* Series E: total tax revenue, baseline variables = [], reform variables = [IIT, CIT, behavior, macro]

We already have series A and E as the respective baseline and reform total tax revenue series. Having the three distinct artificial series B, C, and D, would allow us to have a decomposition table with the following lines.

* IIT effect, B - A (holding CIT, behavior, and macro constant)
* CIT effect, C - B (holding behavior and macro constant)
* behavior effect, D - C (holding macro constant)
* macro effect, E - D

I like the option of combining the IIT and CIT effects into one total tax effect, and I like Ben's idea of the option of combining the behavior and macro effects into one macro feedback effect. But my default would be this particular breakout with all four lines.

This is a matter of preference. I would love to get your thoughts.

**Comment by jdebacker** [comment]
@rickecon I don't know what's up with the code coverage either.  The `test_TPI.py` script is not affected here, so I don't know why there's not coverage of `TPI.inner_loop`, which was covered before.

Regarding you questions about decomposition.  You propose:

> * IIT effect, B - A (holding CIT, behavior, and macro constant)
> * CIT effect, C - B (holding behavior and macro constant)
> * behavior effect, D - C (holding macro constant)
> * macro effect, E - D

Note that CIT rate changes have no direct effect on the IIT+payroll tax revenue and IIT+payroll rate changes have no direct effect on CIT revenue.  So if you want those four changes you note above, you would look to the following rows from the table output (using the `dynamic_revenue_decomposition` function with the options `include_business_tax=True` and `full_break_out=True`):

1. `IIT: Pct Change due to tax rates`
2. `CIT: Pct Change due to tax rates`
3. `All: Pct Change due to behavior`
4.  `All: Pct Change due to macro` 

"All" referes to all taxes (CIT + IIT + payroll).  Additional detail is provided to allow one to see the behavioral/macro contributions to the IIT+payroll tax revenues and the CIT tax revenues separately, but all the splits you are asking about are there.

> I like the option of combining the IIT and CIT effects into one total tax effect, and I like Ben's idea of the option of combining the behavior and macro effects into one macro feedback effect. 

If one wants to lump the behavioral and macro effects together to get a total dynamic revenue effect, one can set the option `full_break_out=False`.  This then returns three items (optionally, three for each of individual, business, and all taxes if `include_business_tax=True`):

1. Static effect
2. Behavior + macro effect (aka dynamic effect - this is what Ben is looking for)
3. Total change in taxes (static + behavior + macro)

Let me know if you still think something is missing.  I've erred on the side of having more detail in the tables.  One can ignore certain rows if one wishes, but I think it's helpful as a diagnostic tool to separately see what is happening with different revenue sources.  I hope this hasn't caused confusion in reading the output.

**Comment by jdebacker** [comment]
@rickecon asks: 

>  Do you care about updating the docstring in this branch's output_tables.py lines 445 to 461? This PR introduces an extra business tax line to the decomposition.

Good catch - just updated those to just generally refer to tax revenue since different sources can be accounted for now.

**Comment by rickecon** [comment]
@jdebacker LGTM.

**Pull request merged**
