### PR TITLE
Code adjustments for clarity

### PR DESCRIPTION
**Pull request by jdebacker**
This PR makes several changes to the code for clarity, with no effect on results.  With these changes, all calculations are done in specific functions and not inline in the the functions used to solve for model equilibria.  This will help reduce errors, ensure all calculations are specifically tested, and help make the code more clear

Changes in this PR include:

1) Creating a function, `household.get_y` to compute household pre-tax income.  Previously this was done in-line in both `SS.py` and `TPI.py`.
2) Updating the `aggregates.get_I` function to compute total investment (not net).  Previously this was done in-line in both `SS.py` and `TPI.py`.
3) Creating a function, `fiscal.get_foreign debt_service` to compute government debt service payments to foreign investors.  Previously this was done in-line in both `SS.py` and `TPI.py`.
4) Removal of some lines of code that we unnecessary.
5) Consolidate the use of `if` statements for different version of the model (e.g., balanced budget, baseline/reform), where possible.
6) Move calculations of IIT and payroll tax revenue into the `aggregates.revenue` function and out of in-line calculations in `SS.py` and `TPI.py`.  Also updates the `revenue` function to return only SS or time paths of aggregate revenue totals (currently some numbers are aggregates and others on a household basis).

### CODE REVIEW

**Comment by jdebacker** [comment]
Note that the `I_total` variable in the TPI results, which computes the total amount of investment by firms (not investment net of flows of capital from immigrants), is now different than before because there had been an indexing error.

**Comment by jdebacker** [comment]
Removing work in progress labels.  PR is tentatively done, but running full test suite locally to be sure before merging.  Will respond with results of that in about 24 hours.

**Comment by rickecon** [comment]
@jdebacker , OK. Looking forward to it.

**Comment by jdebacker** [comment]
@rickecon All tests pass locally.

**Pull request merged**
