### PR TITLE
Bug fixes, mostly related to start year and addition of 2030

### PR DESCRIPTION
**Pull request by jdebacker**
This PR fixes some issues coming from the addition of 2030 to the period over which TC parameters can adjust.  E.g., the need to update the cached tax function estimates.

There are also several changes related to the model start year: changing default to update based on TC and not a hard code in `constants.py`.

### CODE REVIEW

**Comment by rickecon** [comment]
Looks good, @jdebacker. I'll merge it as soon as Travis CI tests pass.

**Comment by jdebacker** [comment]
@rickecon hold off please!  Changing to WIP.  Running estimation for new PUF file now...

**Comment by jdebacker** [comment]
Add fix to deal with Issue #549.

**Comment by jdebacker** [comment]
@rickecon This is not ready for your review after Travis CI tests pass.

**Pull request merged**
