### PR TITLE
Update to run code coverage on GH Action

### PR DESCRIPTION
**Pull request by jdebacker**
This PR updates the `build_and_test` GH Action to produce code coverage reports.

It also tries to run the `pycodestyle` checks.

### CODE REVIEW

**Comment by jdebacker** [comment]
Now pinning `sphinxcontrib-bibtex` version to avoid failure to build Jupyterbook,  per solution suggested [here](https://github.com/executablebooks/jupyter-book/issues/1137).

**Comment by rickecon** [comment]
@jdebacker . What do you think about the codecov diff hit target failing? It looks like the coverage is somehow looking the `tests` folder. I don't understand this.

**Comment by rickecon** [comment]
@jdebacker . Is this OK with 81.64% codecov/project? I am fine with it. If so, then I am ready to merge this.

**Comment by jdebacker** [comment]
@rickecon Yes, I could spend some more time adding coverage with more tests, but let's merge this now.  We need  CI testing working for other PRs.  Thanks.

**Pull request merged**
