### PR TITLE
Jupyter Book documentation

### PR DESCRIPTION
**Pull request by jdebacker**
This PR begins to move OG-USA documentation, both the contributor and API guides that are in Sphinx and the theory documentation in TeX, over to a Jupyter Book.

Screen Shot 2020-07-17 at 10 13 34 PM

### CODE REVIEW

**Comment by jdebacker** [comment]
Now compiling Sphinx docs for the model's API in Jupyter-Book.  This is about the stage I wanted to get to for this PR.  Still plenty of work to do transferring over the theory from TeX to the MyST syntax, but what is in the PR should serve as a helpful guide.

cc @rickecon

**Comment by jdebacker** [comment]
With the latest commits, these Jupyter Book now contains all the theory from the OGUSAdoc pdf:

Screen Shot 2020-07-26 at 5 28 06 PM

There are also examples of executable code that are currently being used to generate figures and tables in the JB.  This will help ensure the all figures in the document represent the calibration of the model (as given in `default_parameters.json`), as well as show users example code to generate these plots/tables:

Screen Shot 2020-07-26 at 5 28 28 PM

Some items that remain:
1) Fix all references, especially those for specific "Chapters" of the theory doc.
2) Ensure that all citations are working as expected.
3) Update tables from teX to markdown.  Is there any quick way to do this?

cc @rickecon

**Comment by jdebacker** [comment]
I've converted most tables from TeX to Markdown with [Pandoc!](https://pandoc.org/try/?text=+&from=latex&to=gfm&standalone=0), though there are still some formatting issues with equations/symbols in the tables that need to be resolved.

Also, I'm not sure how to create table notes, table titles, or labels to reference for tables made in standard markdown syntax.  Jupyter-Book documentations gives an example of a table label and reference using the `list-table` format [here](https://jupyterbook.org/reference/cheatsheet.html?highlight=table%20referene#tables), but no example is provided for tables done in standard markdown.

**Comment by jdebacker** [comment]
Latest commit adds a new chapter, "Citations and use cases of OG-USA", which lists citations compiled in a `citations.bib` file.

**Comment by rickecon** [comment]
@jdebacker . Let's merge this so we have a proper GitHub page with the Jupyter Book as it now stands. Then let's make more changes as incremental PR's. Thoughts?

**Comment by jdebacker** [comment]
@rickecon I think that makes sense.  Let me update the GitHub Action to build and deploy this then we can merge.

**Comment by jdebacker** [comment]
@rickecon Latest commit updates the GH actions to build and deploy the Jupyterbook.

**Comment by rickecon** [comment]
@jdebacker Are you ready for me to merge this, or did you have more commits you wanted to get in?

**Comment by jdebacker** [comment]
@rickecon It's ready.  Please merge if things checkout for you.

**Pull request merged**
